name: flutter_apps_core_lib
description: Flutter library to include some common core components across multiple apps
version: 0.0.1
homepage: www.flognity.com

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  #user_messaging_platform: ^1.2.1
  #google_mobile_ads: ^2.0.0
  provider: ^6.0.3
  flutter_config: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flognity.flutter_apps_core_lib
        pluginClass: FlutterAppsCoreLibPlugin
      ios:
        pluginClass: FlutterAppsCoreLibPlugin