name: flutter_apps_core_lib
description: Flutter library to include some common core components across multiple apps
version: 0.0.1
homepage: www.flognity.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flognity.flutter_apps_core_lib
        pluginClass: FlutterAppsCoreLibPlugin
      ios:
        pluginClass: FlutterAppsCoreLibPlugin